[package]
name = "minilara"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
minijinja = { version = "1", features = ["loader"] }
serde = { version = "1", features = ["derive"] }
dotenv = "0.15.0"
