[package]
name = "macros-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
regex.workspace = true
once_cell.workspace = true
time.workspace = true
serde_json.workspace = true