[package]
name = "rustavel-db"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "database"
path = "src/main.rs"

[dependencies]
rustavel-core = { path = "../core" }
clap.workspace = true
tokio.workspace = true
dotenv.workspace = true
once_cell.workspace = true
async-trait.workspace = true